import { AUTO_DREAM_DEFAULT_DAYS, MANUAL_DREAM_DEFAULT_DAYS } from "../dream-defaults.js";

export function buildDreamPrompt(options?: { mode?: "manual" | "auto"; days?: number }): string {
  const mode = options?.mode === "auto" ? "auto" : "manual";
  const days = Number.isFinite(options?.days) && Number(options?.days) > 0
    ? Math.floor(Number(options?.days))
    : (mode === "auto" ? AUTO_DREAM_DEFAULT_DAYS : MANUAL_DREAM_DEFAULT_DAYS);

  return [
    mode === "auto" ? `auto dream ${days}` : `dream ${days}`,
    "",
    "Perform Dream memory maintenance for this workspace.",
    "",
    "Execution bounds:",
    "- Only modify `notes/daily/` and `notes/memory/` files.",
    "- Do not modify project code, tests, runtime sources, or unrelated config.",
    "- Load memory at session start from `notes/memory/MEMORY.md` and `notes/index.md`, then open deeper files only as needed.",
    "",
    "You are the evaluator for what is relevant. Do not use fixed message-length heuristics; use judgment based on the recent evidence you inspect.",
    "",
    "Follow the original 4-phase Dream flow:",
    "1. Orient:",
    "- Runtime has already created a pre-Dream backup and refreshed/seeded daily note files for this window before you start editing.",
    "- Load startup memory from `notes/memory/MEMORY.md` and `notes/index.md`.",
    "- Inspect relevant `notes/daily/*.md` and existing `notes/memory/*` files before deciding what matters.",
    "- Open deeper files only when they are needed to resolve uncertainty.",
    "2. Signal:",
    "- Look for new information worth persisting.",
    "- Prioritize the daily notes already seeded for this window, then memories that drifted from reality, then narrow transcript/message confirmation only when needed.",
    "- Use rough/narrow searches, not exhaustive transcript reading.",
    "- Only if you need specific confirmation, use narrow `messages.search` queries for terms you already suspect matter.",
    "- Do not sweep the whole transcript history blindly.",
    "3. Consolidate:",
    "- Merge new signal into existing note/memory files instead of creating near-duplicates.",
    "- Convert phrases like 'today' or 'yesterday' into absolute dates.",
    "- If a newer fact disproves an older memory, fix the older source file.",
    "- Update the `## Summary` section for each daily note in scope so it reflects the final understanding for that day.",
    "- For partially summarised days, keep the Summary update flow coherent and advance `summarised_until` to the day's `last_message` when the note is fully brought up to date.",
    "- Keep `notes/daily/` and `notes/memory/` aligned as two layers of the same final state.",
    "4. Prune and Index:",
    "- Remove obsolete pointers, redundant notes, and index entries that no longer help.",
    "- Add pointers to newly important memories that future sessions should be able to find quickly.",
    "- Keep `notes/memory/MEMORY.md` compact, one-line-per-entry, and under the startup budget.",
    "- If an index line is overly verbose, shorten it and move the detail into the linked memory file instead of carrying content in the index.",
    "- The runtime will refresh workspace FTS indexing after your Dream pass completes; you do not need to perform infrastructure housekeeping yourself.",
    "",
    `Window: focus on the last ${days} day(s).`,
    "",
    "Required outputs:",
    "- Keep `notes/daily/` as the concise human-readable overview layer.",
    "- Keep `notes/memory/` as the durable agent-memory layer.",
    "- Keep `notes/memory/MEMORY.md` as an index only: compact, one-line entries, and under the startup budget.",
    "- Update typed memory files (`user.md`, `feedback.md`, `project.md`, `reference.md`) only if the new signal actually changes them.",
    "- Keep `notes/memory/current-state.md` and `notes/memory/recent-context.md` aligned with your final consolidated state.",
    "- Treat `notes/memory/days/*.md` as optional sparse episodic memory: create, update, or prune them only when a day carries durable agent-facing signal beyond the human-readable daily note.",
    "- Do not create or depend on JSON sidecars; keep durable Dream memory surfaces in Markdown.",
    "- Keep daily-note front matter truthful, especially `summarised_until`, `first_message`, and `last_message` when you touch a note.",
    "",
    "Return a brief summary of what changed across Orient, Signal, Consolidate, and Prune and Index, plus whether runtime post-processing succeeded.",
  ].join("\n");
}
